name: Dynmap-SimpleClans
main: net.sacredlabyrinth.phaed.dynmap.simpleclans.DynmapSimpleClans
version: 1.0
author: phaed
softdepend: [ dynmap, SimpleClans ]
commands:
  map:
    description: Map commands
    usage: Syntax error, verify the command usage and try again
permissions:
  simpleclans.map.toggle:
    description: Can toggle map visibility
