name: Dynmap-SimpleClans
main: net.sacredlabyrinth.phaed.dynmap.simpleclans.DynmapSimpleClans
version: 1.2
authors: [ phaed, BangL ]
softdepend: [ dynmap, SimpleClans ]

commands:
  map:
    description: Map commands
    usage: Syntax error, verify the command usage and try again
permissions:
  simpleclans.map.toggle:
    description: Can toggle map visibility
